### ISSUE TITLE
set save.nwstats = FALSE in control.net

### ISSUE THREAD

**Issue by thednainus** [EpiModel/EpiModel#626] opened 2022-01-27 15:16 UTC
Hello,

I have noticed that if I set `save.nwstats = FALSE` in `control.net` function and run the simulation as 
`sim <- netsim(est, param, init, control)`
When I check the content of `sim`, it prints some info and also the following error message:
_Error in colMeans(merged.stats) :   'x' must be an array of at least two dimensions_

You can replicate the same error message by running the covid model from the EpiModel workshop:
http://statnet.org/nme/d5-s6-COVIDScreen.html

This error specifically appears here
http://statnet.org/nme/d5-s6-COVIDScreen.html#Model_Analysis
and only when setting `save.nwstats = FALSE`

I suspect it is nothing serious, but maybe some scripts got modified and printing the content of `sim` generates now this error message.

Cheers,
Fabricia.

Cheers,
Fabricia.

**Comment by smjenness** [comment] 2022-01-27 21:26
@AdrienLeGuillou Could you take a look at this potential bug?

**Comment by AdrienLeGuillou** [comment] 2022-01-28 09:08
Hi @thednainus,
thanks for the report, I can indeed reproduce that with the CRAN version of EpiModel.

However it disappeared on my end when using the last GitHub version. Could you give that a try?

You can install the last dev version with `renv::install("EpiModel/EpiModel")` if you use [`renv`](https://rstudio.github.io/renv/index.html) (highly recommended) or `remotes::install_github("EpiModel/EpiModel")` otherwise.

Thanks

**Comment by smjenness** [comment] 2022-01-28 14:18
Ah yes, it looks like I fixed that 12/15/21 here: https://github.com/EpiModel/EpiModel/commit/d4002714ea148e01f162d77770f700b7690ebe3d.

Closing issue.

**Closed by smjenness** 2022-01-28 14:18 UTC
Labels: bug
