### ISSUE TITLE
stochastic vignette failure

### ISSUE THREAD

**Issue by chad-klumb** [EpiModel/EpiModel#710] opened 2022-06-24 22:47 UTC
model-parameters.Rmd randomly fails with error message "polygon edge not found", e.g.

https://github.com/EpiModel/EpiModel/runs/7046147895?check_suite_focus=true#step:6:168

(line 166 in the link)

This isn't new, but we might want to consider addressing it.  (I've only seen it happen in the mac build for EpiModel.)

**Comment by AdrienLeGuillou** [comment] 2022-07-07 15:08
For ref:

The issue is probably related to a `ggplot` call. This thread seems to depict a similar problem:
https://community.rstudio.com/t/build-failure-for-check-release-workflow/107368/3

**Comment by chad-klumb** [comment] 2022-07-07 18:18
fwiw, this error just happened in the PR build for #693:

https://github.com/EpiModel/EpiModel/runs/7238793829?check_suite_focus=true#step:6:157

**Comment by smjenness** [comment] 2022-07-07 19:03
Fixed with 0e6eb14f220b89e0f5db9d13ad293da3dd7fc0b7

**Closed by smjenness** 2022-07-07 19:03 UTC
